# Generated by Django 3.0.3 on 2020-07-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200714_0522'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='OrderID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
