# Generated by Django 3.0.3 on 2020-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200715_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=None, verbose_name='Contact phone number'),
        ),
    ]
