# Generated by Django 3.0.3 on 2020-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200715_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='Phone'),
        ),
    ]
