# Generated by Django 3.0.3 on 2020-07-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200715_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=11, verbose_name='Phone'),
        ),
    ]
