# Generated by Django 3.0.3 on 2020-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
