# Generated by Django 3.0.3 on 2020-07-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('orders', '0002_auto_20200713_0318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='TakeOrder',
        ),
    ]
