# Generated by Django 3.0.3 on 2020-07-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('orders', '0003_auto_20200714_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.FloatField(null=True)),
                ('net_amount', models.IntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='takeorder',
            name='order_date',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('TakeOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.TakeOrder')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='OrderDetailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDetail'),
        ),
    ]
