# Generated by Django 3.0.3 on 2020-07-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200714_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderDetailID',
        ),
    ]
