# Generated by Django 3.0.3 on 2020-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200717_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount',
            field=models.IntegerField(null=True),
        ),
    ]
