# Generated by Django 3.0.3 on 2020-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200718_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeorder',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
