# Generated by Django 3.0.3 on 2020-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200718_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='TakeOrder',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(default='product', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
