# Generated by Django 3.0.3 on 2020-07-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200719_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='customer', max_length=100)),
                ('order_id', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
