# Generated by Django 3.0.3 on 2020-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_currentorderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
