# Generated by Django 3.0.3 on 2020-07-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200723_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderID',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
