# Generated by Django 3.0.3 on 2020-07-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200723_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
