# Generated by Django 3.0.3 on 2020-07-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('orders', '0028_auto_20200725_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='productID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
