# Generated by Django 3.0.3 on 2020-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200725_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='productID',
            new_name='product',
        ),
    ]
